"""Export a selection of datasets to a runnable marimo app or a Colab notebook.

Both artifacts are self-contained: they ``pip install`` psidata, fetch the exact source files by URL
(handling archives and files packaged inside a published BagIt/zip), parse them with the same readers,
and rebuild an equivalent Plotly figure. "Open in marimo / Colab" is therefore reproducible — a live
starting point for analysis, not a screenshot.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

import nbformat

#: Package spec the generated notebooks install. psidata isn't on PyPI yet, so install it straight from
#: the public repo's subdirectory (the ``[convert]`` extra pulls the binary/format readers).
PACKAGE_SPEC = (
    "psidata[convert] @ git+https://github.com/jyarger/PsiDataViz.git#subdirectory=packages/psidata"
)


@dataclass(frozen=True)
class ExportItem:
    """One dataset to reproduce: a display name, the raw URL, the technique hint, and (for a dataset
    inside a multi-dataset archive) the member to load."""

    name: str
    url: str
    technique: str | None = None
    member: str | None = None


def _items_literal(items: list[ExportItem]) -> str:
    return json.dumps([[it.name, it.url, it.technique, it.member] for it in items], indent=4)


# --- shared body that loads + plots, embedded into both artifacts -----------------------------
def _plot_body(items: list[ExportItem], x_quantity: str) -> str:
    return f'''import io
import os
import zipfile

import httpx
import plotly.graph_objects as go
from psidata import Candidate, is_archive, read, read_archive

# (display name, raw file URL, technique hint, archive member) for each selected dataset
DATASETS = {_items_literal(items)}
X_QUANTITY = {x_quantity!r}  # "temperature" or "time" (DSC only)


def fetch(url):
    return httpx.get(url, follow_redirects=True, timeout=120).content


def load(name, url, technique, member=None):
    if ".zip!" in url:  # a file packaged inside a published archive (e.g. a Chemotion BagIt zip)
        zip_url, inner = url.split(".zip!", 1)
        data = zipfile.ZipFile(io.BytesIO(fetch(zip_url + ".zip"))).read(inner)
        return read(Candidate(filename=os.path.basename(inner), content=data, technique_hint=technique))
    content = fetch(url)
    if is_archive(name) or is_archive(url):
        return read_archive(name, content, technique_hint=technique, member=member)
    return read(Candidate(filename=name, content=content, uri=url, technique_hint=technique))


def x_column(signal):
    if X_QUANTITY == "time":
        for col in signal.frame.columns:
            if "time" in col.lower():
                return col
    return signal.x.label


fig = go.Figure()
x_title = y_title = ""
reverse_x = False
datasets = []
for name, url, technique, member in DATASETS:
    ds = load(name, url, technique, member)
    datasets.append(ds)  # keep the parsed datasets around (ds.images holds 2D NMR / detector maps)
    sample = ds.metadata.sample_name or name
    if ds.technique in ("NMR", "FTIR"):
        reverse_x = True  # NMR/FTIR convention: abscissa decreases left->right
    for sig in ds.signals:
        x_title, y_title = sig.x.title, sig.y.title
        fig.add_scatter(
            x=sig.frame[x_column(sig)], y=sig.frame[sig.y.label], mode="lines",
            name=f"{{sample}} · {{sig.segment or sig.name}}",
        )
fig.update_layout(template="plotly_white", xaxis_title=x_title, yaxis_title=y_title,
                  legend_title="Dataset")
if reverse_x:
    fig.update_xaxes(autorange="reversed")
fig'''


def to_marimo(items: list[ExportItem], x_quantity: str = "temperature") -> str:
    """Return the source of a runnable marimo app (``.py``) reproducing the figure. The PEP 723 script
    header lets ``marimo edit --sandbox`` (and molab) install the dependencies automatically."""
    body = _plot_body(items, x_quantity)
    indented = "\n".join("    " + line if line else "" for line in body.splitlines())
    return f'''# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "{PACKAGE_SPEC}",
#     "plotly",
#     "httpx",
# ]
# ///
import marimo

app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    mo.md("# PsiData export\\n\\nInteractive view of {len(items)} dataset(s). Run all cells.")
    return (mo,)


@app.cell
def _():
{indented}


if __name__ == "__main__":
    app.run()
'''


def to_colab(items: list[ExportItem], x_quantity: str = "temperature") -> bytes:
    """Return a Colab/Jupyter notebook (``.ipynb`` bytes) reproducing the figure."""
    nb = nbformat.v4.new_notebook()
    nb.cells = [
        nbformat.v4.new_markdown_cell(
            "# PsiData export\n\n"
            f"Interactive view of {len(items)} dataset(s), generated by PsiDataViz. "
            "Run the cells top to bottom."
        ),
        nbformat.v4.new_code_cell(f'!pip install -q "{PACKAGE_SPEC}" plotly httpx'),
        nbformat.v4.new_code_cell(_plot_body(items, x_quantity)),
    ]
    nb.metadata["language_info"] = {"name": "python"}
    return nbformat.writes(nb).encode("utf-8")
